import sqlite3
from tkinter import *
from tkinter import ttk

root=Tk()
root.geometry("250x200")
root.resizable(0,0)
conexion=sqlite3.connect("agenda.db")
cursor=conexion.cursor()
titulo_opciones=Label(root,text="¿Que desea realizar?",font=("Curier 12")).pack()

def Agregar():
    def Guardar_tarea():
        cursor.execute(f'INSERT INTO TAREAS VALUES(NULL,"{dias.get()}","{tarea.get()}","{entrega.get()}")')
        conexion.commit()
        root_agregar.destroy()
    tarea=StringVar()
    entrega=StringVar()
    dias=StringVar()
    root_agregar=Toplevel()
    root_agregar.geometry("500x400")
    Label(root_agregar,text="¿Que tarea quiere agregar?",font=("Curier 10")).pack(pady=5)
    Entry(root_agregar,textvariable=tarea,width=30).pack()
    Label(root_agregar,text="¿Que dia desea guardar",font=("Curier 10")).pack(pady=5)
    dias_op=["Lunes","Martes","Miercoles","Jueves","Viernes"]
    list_de_tareadia=ttk.Combobox(root_agregar,width=27,values=dias_op,textvariable=dias).pack()
    Label(root_agregar,text="¿Que fecha se entrega?",font=("Curier 10")).pack(pady=5)
    Entry(root_agregar,textvariable=entrega,width=30).pack()
    Button(root_agregar,text="Guardar tarea",font=("Curier 10"),width=15,command=Guardar_tarea).pack(pady=10)

def Eliminar():
    def Eliminar_commit():
        cursor.execute(f'DELETE FROM TAREAS WHERE ID={id.get()}')
        conexion.commit()
        root_eliminar.destroy()
    root_eliminar=Toplevel()
    root_eliminar.geometry("600x300")
    id=IntVar()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Lunes"')
    ver1=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Martes"')
    ver2=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Mieroles"')
    ver3=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Jueves"')
    ver4=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Mieroles"')
    ver5=cursor.fetchall()
    tareas=Listbox(root_eliminar)
    tareas.insert(1,f'Lunes:{ver1}',f'Martes:{ver2}',f'Miercoles:{ver3}',f'Jueves:{ver4}',f'Vienres:{ver5}')
    tareas.pack(fill="both")
    Label(root_eliminar,text="¿Que ID de tarea desea eliminar?",font=("Curier 10")).pack(pady=10)
    Entry(root_eliminar,textvariable=id,width=30).pack()
    Button(root_eliminar,text="Eliminar",width=15,command=Eliminar_commit).pack(pady=10)

def Ver():
    root_ver=Toplevel()
    root_ver.geometry("600x300")
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Lunes"')
    ver1=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Martes"')
    ver2=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Mieroles"')
    ver3=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Jueves"')
    ver4=cursor.fetchall()
    cursor.execute('SELECT * FROM TAREAS WHERE DIA="Mieroles"')
    ver5=cursor.fetchall()
    tareas=Listbox(root_ver)
    tareas.insert(1,f'Lunes:{ver1}',f'Martes:{ver2}',f'Miercoles:{ver3}',f'Jueves:{ver4}',f'Vienres:{ver5}')
    tareas.pack(fill="both")
agregar_tarea=Button(root,text="Agregar tarea",font=("Curier 9"),command=Agregar,width=15).pack(pady=5)
eliminar_tarea=Button(root,text="Eliminar tarea",font=("Curier 9"),width=15,command=Eliminar).pack(pady=5)
ver_tarea=Button(root,text="Ver las tareas",font=("Curier 9"),width=15,command=Ver).pack(pady=5)

root.mainloop()
conexion.close()